module.exports = {
  FETCH_LISTS: 'FETCH_LISTS',
  ADD_LIST: 'ADD_LIST',
  SET_USERID: 'SET_USERID',
  SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
  SET_SUCCESS_MESSAGE: 'SET_SUCCESS_MESSAGE',
  SET_SHARE_LIST: 'SET_SHARE_LIST'
};
